# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/paathai',
                'doc_host': 'https://numb3r33.github.io',
                'git_url': 'https://github.com/numb3r33/paathai',
                'lib_path': 'paathai'},
  'syms': {'paathai.core': {}, 'paathai.data': {}}}
