# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/paath.ai',
                'doc_host': 'https://numb3r33.github.io',
                'git_url': 'https://github.com/numb3r33/paath.ai',
                'lib_path': 'paath.ai'},
  'syms': {'paath.ai.core': {'paath.ai.core.foo': ('core.html#foo', 'paath.ai/core.py')}}}
